// Shared course/physics core for Mobius arbitrary-level work.
// UMD-style: works in browser globals and Node/CommonJS.
(function(root,factory){
  const api=factory();
  if(typeof module==='object'&&module.exports)module.exports=api;
  root.MobiusCourse=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const TAU=Math.PI*2,R=5.3,W=1.4;
const MAX_SPEED=1.045,ACCEL=.38,DRAG=.22,TURN=1.99,SIDE_SCALE=.58,BUMPER_MARGIN=.16;
const DEFAULT_PHYS_HZ=120;
function positiveMod(x,m){return ((x%m)+m)%m}
function clamp(x,a,b){return Math.max(a,Math.min(b,x))}
function v(x=0,y=0,z=0){return{x,y,z}}
function add(a,b){return v(a.x+b.x,a.y+b.y,a.z+b.z)}
function sub(a,b){return v(a.x-b.x,a.y-b.y,a.z-b.z)}
function mul(a,s){return v(a.x*s,a.y*s,a.z*s)}
function dot(a,b){return a.x*b.x+a.y*b.y+a.z*b.z}
function cross(a,b){return v(a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x)}
function lenSq(a){return dot(a,a)}
function len(a){return Math.sqrt(lenSq(a))}
function norm(a){const l=len(a);return l>1e-12?mul(a,1/l):v(0,0,0)}
function addScaled(a,b,s){return v(a.x+b.x*s,a.y+b.y*s,a.z+b.z*s)}
function projectOnPlane(a,n){return sub(a,mul(n,dot(a,n)))}
function applyAxisAngle(vec,axis,angle){const u=norm(axis),c=Math.cos(angle),s=Math.sin(angle);return add(add(mul(vec,c),mul(cross(u,vec),s)),mul(u,dot(u,vec)*(1-c)))}
function levelParams(level){const baseCols=143;return{level,cols:level==='diamond'?144:(level==='figure8'?221:(level==='trefoil'?199:baseCols)),sideCols:level==='diamond'?143:(level==='figure8'?221:(level==='trefoil'?199:baseCols)),rows:(level==='mobius'||level==='figure8')?18:12}}
function plainMobiusPoint(t,s){const rr=3.25+s*Math.cos(t/2);return v(rr*Math.cos(t),rr*Math.sin(t),s*Math.sin(t/2))}
const FIG8_X=5.25,FIG8_Y=2.55,FIG8_Z=2.05,TREFOIL_SCALE=1.40;
function figure8Center(t){return v(FIG8_X*Math.sin(t),FIG8_Y*Math.sin(2*t),FIG8_Z*Math.cos(t))}
function trefoilCenter(t){return v((2+Math.cos(3*t))*Math.cos(2*t)*TREFOIL_SCALE,(2+Math.cos(3*t))*Math.sin(2*t)*TREFOIL_SCALE,Math.sin(3*t)*TREFOIL_SCALE)}
function numericTangent(fn,t){const e=.001;return norm(sub(fn(t+e),fn(t-e)))}
function figure8Tangent(t){return numericTangent(figure8Center,t)}
function trefoilTangent(t){return numericTangent(trefoilCenter,t)}
function widthDirection(centerTan,t){const up=v(0,0,1);let w=cross(up,centerTan);if(lenSq(w)<1e-6)w=v(1,0,0);return norm(applyAxisAngle(norm(w),centerTan,t/2))}
function figure8WidthDirection(t){return widthDirection(figure8Tangent(t),t)}
function trefoilWidthDirection(t){return widthDirection(trefoilTangent(t),t)}
function rawPoint(level,t,s){if(level==='mobius')return plainMobiusPoint(t,s);if(level==='figure8')return addScaled(figure8Center(t),figure8WidthDirection(t),s);if(level==='trefoil')return addScaled(trefoilCenter(t),trefoilWidthDirection(t),s*.72);return v(R*Math.cos(t),R*Math.sin(t),s)}
function tangentT(level,t,s){if(level==='diamond')return norm(v(-Math.sin(t),Math.cos(t),0));const e=.001;return norm(sub(rawPoint(level,t+e,s),rawPoint(level,t-e,s)))}
function tangentS(level,t,s){if(level==='diamond')return v(0,0,1);const e=.001;return norm(sub(rawPoint(level,t,s+e),rawPoint(level,t,s-e)))}
function normal(level,t,s){if(level==='diamond')return norm(v(-Math.cos(t),-Math.sin(t),0));return norm(cross(tangentT(level,t,s),tangentS(level,t,s)))}
function isNonOrientableMainLevel(level){return level==='mobius'||level==='figure8'||level==='trefoil'}
function cellIndex(c,r,rows){return c*rows+r}
function decodeCells(str,cols,rows,grid='main'){const out=new Array(cols*rows);for(let i=0;i<out.length;i++){const n=+(str[i]||0);out[i]={frontOn:!!(n&1),backOn:!!(n&2),col:Math.floor(i/rows),row:i%rows,grid}}return out}
function encodeCells(cells){return cells.map(c=>(c.frontOn?1:0)|(c.backOn?2:0)).join('')}
function normalizeMain(level,cols,rows,c,r){let sideFlip=false;c=positiveMod(c,cols);if(r<0||r>=rows){if(isNonOrientableMainLevel(level)){r=r<0?rows-1:0;c=positiveMod(c+Math.floor(cols/2),cols);sideFlip=true}else r=clamp(r,0,rows-1)}return{c,r,sideFlip}}
function stepGrid(gridCells,cols,rows,normalizer){const next=gridCells.map(()=>({front:false,back:false}));for(const cell of gridCells){for(const sideName of ['frontOn','backOn']){let count=0;for(let dc=-1;dc<=1;dc++)for(let dr=-1;dr<=1;dr++){if(!dc&&!dr)continue;const n=normalizer(cell.col+dc,cell.row+dr);const nc=gridCells[cellIndex(n.c,n.r,rows)];const key=n.sideFlip?(sideName==='frontOn'?'backOn':'frontOn'):sideName;if(nc&&nc[key])count++}const alive=cell[sideName];const out=alive?(count===2||count===3):(count===3);if(sideName==='frontOn')next[cellIndex(cell.col,cell.row,rows)].front=out;else next[cellIndex(cell.col,cell.row,rows)].back=out}}for(const cell of gridCells){const n=next[cellIndex(cell.col,cell.row,rows)];cell.frontOn=n.front;cell.backOn=n.back}}
function normalizeSide(cols,rows,c,r){c=positiveMod(c,cols);let sideFlip=false;if(r<0||r>=rows){r=r<0?rows-1:0;c=positiveMod(c+Math.floor(cols/2),cols);sideFlip=true}return{c,r,sideFlip}}
function stepLife(state){stepGrid(state.cells,state.cols,state.rows,(c,r)=>normalizeMain(state.level,state.cols,state.rows,c,r));if(state.level==='diamond'&&state.sideCells)stepGrid(state.sideCells,state.sideCols,state.rows,(c,r)=>normalizeSide(state.sideCols,state.rows,c,r))}
function computeWorldHashFromCells(cells,sideCells=[]){let h1=0x811c9dc5,h2=0xc2b2ae35;function mix(x){h1=Math.imul(h1^x,0x01000193)>>>0;h2=Math.imul(h2^(x+0x9e3779b9),0x85ebca6b)>>>0}for(const c of [...(cells||[]),...(sideCells||[])]){mix((c.col<<16)|c.row|((c.grid==='side')?0x80000000:0)|((c.frontOn?1:0)<<14)|((c.backOn?1:0)<<15))}return('0000000'+h1.toString(16)).slice(-8)+('0000000'+h2.toString(16)).slice(-8)}
function terrainKind(cell,faceSign){if(!cell)return'none';const here=faceSign>=0?cell.frontOn:cell.backOn,there=faceSign>=0?cell.backOn:cell.frontOn;if(here&&there)return'hazard';if(here)return'boost';if(there)return'mud';return'none'}
function terrainRank(kind){return kind==='hazard'?3:(kind==='mud'?2:(kind==='boost'?1:0))}
function renderedMainTerrainCoords(state,t,sVal,faceSign){let sRendered=sVal,face=faceSign,lap=Math.floor(t/TAU);if(isNonOrientableMainLevel(state.level)&&Math.abs(lap%2)===1){sRendered=-sRendered;face*=-1}const c=clamp(Math.floor(positiveMod(t,TAU)/TAU*state.cols),0,state.cols-1),r=clamp(Math.floor((clamp(sRendered,-W,W)+W)/(2*W)*state.rows),0,state.rows-1);return{c,r,faceSign:face,lap,sRendered}}
function currentTerrainCell(state){const rowFootprint=1.02,rowWidth=2*W/state.rows,samples=[state.race.s,state.race.s-rowWidth*rowFootprint/2,state.race.s+rowWidth*rowFootprint/2];let fallback=null,best=null,bestRank=-1;for(const sVal of samples){const m=renderedMainTerrainCoords(state,state.race.t,sVal,state.race.faceSign),cell=state.cells[cellIndex(m.c,m.r,state.rows)],hit={cell,faceSign:m.faceSign,key:`main:${m.c}:${m.r}:${m.faceSign}`,coords:m},rank=terrainRank(terrainKind(cell,m.faceSign));if(!fallback)fallback=hit;if(rank>bestRank){bestRank=rank;best=hit}}return bestRank>0?best:fallback}
function mainRouteFrame(state,t=state.race.t,s=state.race.s){const baseUp=normal(state.level,t,s),up=mul(baseUp,state.race.faceSign||1),along=norm(projectOnPlane(tangentT(state.level,t,s),up)),across=norm(projectOnPlane(tangentS(state.level,t,s),up));return{patchId:'main',contact:rawPoint(state.level,t,s),up,baseUp,along,across,alongMetric:R,acrossMetric:1}}
function currentRouteFrame(state){return mainRouteFrame(state)}
function tangentPlaneHeading(state,up,fallback){if(!state.race.headingVec||lenSq(state.race.headingVec)<1e-6)state.race.headingVec={...fallback};state.race.headingVec=projectOnPlane(state.race.headingVec,up);if(lenSq(state.race.headingVec)<1e-6)state.race.headingVec={...fallback};state.race.headingVec=norm(state.race.headingVec);return state.race.headingVec}
function applyRaceTerrain(state,dt){const race=state.race;race.boostTimer=Math.max(0,race.boostTimer-dt);race.mudTimer=Math.max(0,race.mudTimer-dt);race.spinTimer=Math.max(0,race.spinTimer-dt);const t=currentTerrainCell(state),kind=terrainKind(t.cell,t.faceSign);if(kind!=='none'&&t.key!==race.lastTerrainKey){if(kind==='boost'){race.boostTimer=1.15;race.speed=Math.min(MAX_SPEED*1.24,race.speed+.112)}else if(kind==='mud'){race.mudTimer=.45}else if(kind==='hazard'){race.spinTimer=.65;race.speed*=.55}race.lastTerrainKey=t.key}else if(kind==='none'){race.lastTerrainKey=null}if(race.mudTimer>0)race.speed*=Math.exp(-2.85*dt);if(race.spinTimer>0){race.speed*=Math.exp(-2.8*dt);race.headingVec=applyAxisAngle(race.headingVec||mainRouteFrame(state).along,mainRouteFrame(state).up,3.2*dt)}}
function edgeBump(state,sign=1,strength=1){const race=state.race;const speedMul=1+(0.55-1)*clamp(strength,0,1);race.speed*=speedMul;race.lateralSpeed+=sign*.34*strength;if(race.headingVec){const fr=currentRouteFrame(state);race.headingVec=norm(projectOnPlane(addScaled(race.headingVec,fr.across,sign*.42*strength),fr.up))}}
function wallScrape(state,sign,dt){const race=state.race,fr=currentRouteFrame(state);race.speed*=Math.exp(-2.4*dt);if(race.headingVec)race.headingVec=norm(projectOnPlane(addScaled(race.headingVec,fr.across,sign*.6*dt),fr.up));race.lateralSpeed*=Math.exp(-6*dt);race._wallScrapeCool=(race._wallScrapeCool||0)-dt;if(race._wallScrapeCool<=0)race._wallScrapeCool=.28}
function lapCompletionEnabled(level){return level==='mobius'||level==='figure8'||level==='trefoil'}
function checkLapCompletion(state,prevT,newT){const race=state.race;if(!lapCompletionEnabled(state.level)||state.finished)return;const prevDelta=prevT-race.lapStartT,newDelta=newT-race.lapStartT;const prevLap=Math.floor(Math.abs(prevDelta)/TAU),newLap=Math.floor(Math.abs(newDelta)/TAU);if(newLap>prevLap){const dt=1/(state.physHz||DEFAULT_PHYS_HZ);state.finished={kind:'lap',time:+(race.lapTime+dt).toFixed(6),frame:state.frame+1};race.lapTime=0;race._skipLapTimeIncrement=true;race.lapIndex=(race.lapIndex||0)+1;race.lapStartT=newT}}
function stepPhysics(state,bits){const dt=1/(state.physHz||DEFAULT_PHYS_HZ),race=state.race;race.sideCooldown=Math.max(0,(race.sideCooldown||0)-dt);race.transitionGrace=Math.max(0,(race.transitionGrace||0)-dt);if(bits&1){const sr=clamp(race.speed/MAX_SPEED,0,1);race.speed+=ACCEL*Math.pow(1-sr,1.35)*dt}if(bits&2)race.speed-=ACCEL*.85*dt;const turnInput=((bits&4)?1:0)+((bits&8)?-1:0);race.speed*=Math.exp(-(DRAG+(turnInput?0.11:0))*dt);applyRaceTerrain(state,dt);const maxNow=MAX_SPEED*(race.boostTimer>0?1.20:1);race.speed=clamp(race.speed,-MAX_SPEED*.38,maxNow);let f0=currentRouteFrame(state),heading=tangentPlaneHeading(state,f0.up,f0.along),steer=turnInput;race.headingVec=norm(projectOnPlane(applyAxisAngle(heading,f0.up,steer*TURN*(.35+clamp(Math.abs(race.speed)/MAX_SPEED,0,1)*.95)*dt),f0.up));const h=tangentPlaneHeading(state,f0.up,f0.along),alongC=clamp(dot(h,f0.along),-1,1),sideC=clamp(dot(h,f0.across),-1,1),world=race.speed*f0.alongMetric,alongW=world*alongC,sideW=world*sideC*SIDE_SCALE;race.lateralSpeed=sideW;const prevT=race.t;race.t+=alongW/Math.max(.001,f0.alongMetric)*dt;race.s+=sideW*dt;checkLapCompletion(state,prevT,race.t);const limit=W-BUMPER_MARGIN;if(race.s>limit){const fresh=race._lastSAtWall!=='pos';race.s=limit;if(fresh)edgeBump(state,-1,1);else wallScrape(state,-1,dt);race._lastSAtWall='pos'}else if(race.s<-limit){const fresh=race._lastSAtWall!=='neg';race.s=-limit;if(fresh)edgeBump(state,1,1);else wallScrape(state,1,dt);race._lastSAtWall='neg'}else{race._lastSAtWall=null}if(race._skipLapTimeIncrement)race._skipLapTimeIncrement=false;else race.lapTime+=dt;const fr=currentRouteFrame(state);race.upVec=fr.up;return state.finished||null}
function makeStateFromSnapshot(run){const snap=run.snapshot||{},p=levelParams(run.level||snap.level||'mobius'),pose=snap.pose||{};return{level:p.level,cols:snap.cols||p.cols,sideCols:snap.sideCols||p.sideCols,rows:snap.rows||p.rows,physHz:snap.physHz||DEFAULT_PHYS_HZ,lifeEvery:snap.lifeEvery||Math.max(1,Math.round(.22*(snap.physHz||DEFAULT_PHYS_HZ))),lifeRunning:!!snap.lifeRunning,lifeStepCounter:snap.lifeStepCounter||0,cells:decodeCells(snap.cells||'',snap.cols||p.cols,snap.rows||p.rows,'main'),sideCells:[],frame:0,finished:null,race:{route:'main',t:pose.t||0,s:pose.s||0,sideQ:0,sideU:.5,sideDir:1,faceSign:pose.faceSign||1,sideFaceSign:1,speed:pose.speed||0,lateralSpeed:pose.lateralSpeed||0,headingVec:pose.headingVec?{...pose.headingVec}:null,upVec:pose.upVec?{...pose.upVec}:null,boostTimer:pose.boostTimer||0,mudTimer:pose.mudTimer||0,spinTimer:pose.spinTimer||0,lastTerrainKey:null,sideCooldown:0,transitionGrace:0,lapTime:0,lapIndex:0,lapStartT:pose.t||0,_lastSAtWall:null,_lastSideAtWall:null,_wallScrapeCool:0}}}
function inputBitsAt(inputs,frame,cursorObj){let cursor=cursorObj.i,bits=cursorObj.bits;while(cursor<inputs.length&&inputs[cursor].frame<=frame){bits=inputs[cursor].bits|0;cursor++}cursorObj.i=cursor;cursorObj.bits=bits;return bits}
function verifyRun(run,opts={}){const state=makeStateFromSnapshot(run),inputs=(run.inputs||[]).slice().sort((a,b)=>a.frame-b.frame),hasExpectedFrame=typeof run.finished?.frame==='number',targetFrame=hasExpectedFrame?run.finished.frame:(opts.frames??opts.maxFrames??Math.round((state.physHz||DEFAULT_PHYS_HZ)*300)),cursor={i:0,bits:0};const startHash=computeWorldHashFromCells(state.cells,state.sideCells);const failures=[];if(run.snapshot?.worldHash&&startHash!==run.snapshot.worldHash)failures.push(`start hash mismatch ${startHash} != ${run.snapshot.worldHash}`);for(let frame=0;frame<=targetFrame;frame++){state.frame=frame;const bits=inputBitsAt(inputs,frame,cursor);stepPhysics(state,bits);if(state.lifeRunning){state.lifeStepCounter++;if(state.lifeStepCounter>=state.lifeEvery){state.lifeStepCounter=0;stepLife(state)}}if(state.finished&&opts.stopOnFinish!==false)break}if(!state.finished)state.frame=targetFrame;const endHash=computeWorldHashFromCells(state.cells,state.sideCells);const expectedEnd=run.finished?.worldHashEnd;const expectedTime=run.finished?.time;const timeOk=typeof expectedTime!=='number'||!state.finished||Math.abs(state.finished.time-expectedTime)<=1e-6;const frameOk=!run.finished||!state.finished||state.finished.frame===run.finished.frame;const kindOk=!run.finished||!state.finished||state.finished.kind===run.finished.kind;if(expectedEnd&&endHash!==expectedEnd)failures.push(`end hash mismatch ${endHash} != ${expectedEnd}`);if(!state.finished)failures.push('replay did not finish');else{if(!timeOk)failures.push(`time mismatch ${state.finished.time} != ${expectedTime}`);if(!frameOk)failures.push(`frame mismatch ${state.finished.frame} != ${run.finished.frame}`);if(!kindOk)failures.push(`kind mismatch ${state.finished.kind} != ${run.finished.kind}`)}return{pass:failures.length===0,failures,summary:{level:state.level,framesSimulated:state.frame,startHash,endHash,finished:state.finished,expected:run.finished,inputDeltas:inputs.length,lifeStepCounter:state.lifeStepCounter},state}}
return{positiveMod,clamp,v,add,sub,mul,dot,cross,lenSq,len,norm,addScaled,projectOnPlane,applyAxisAngle,levelParams,rawPoint,tangentT,tangentS,normal,isNonOrientableMainLevel,cellIndex,decodeCells,encodeCells,normalizeMain,stepLife,computeWorldHashFromCells,terrainKind,terrainRank,renderedMainTerrainCoords,currentTerrainCell,mainRouteFrame,currentRouteFrame,tangentPlaneHeading,applyRaceTerrain,edgeBump,wallScrape,lapCompletionEnabled,checkLapCompletion,stepPhysics,makeStateFromSnapshot,verifyRun,constants:{TAU,R,W,MAX_SPEED,ACCEL,DRAG,TURN,SIDE_SCALE,BUMPER_MARGIN,DEFAULT_PHYS_HZ}};
});
